<<<<<<< HEAD
/**
 This class allow to describe set of events which occurred on one of the channels and passed to the user.

 @author Sergey Mamontov
 @version 3.4.0
 @copyright © 2009-13 PubNub Inc.
 */
=======
//
//  PNChannelEvents.h
// 
//
//  Created by moonlight on 1/15/13.
//
//


#import <Foundation/Foundation.h>


>>>>>>> fix-pt65153600
@interface PNChannelEvents : NSObject


#pragma mark Properties

<<<<<<< HEAD
/**
 Stores list of events which occurred on channel (presence events and message from other channel participants).
 */
@property (nonatomic, readonly, strong) NSArray *events;

/**
 Stores reference on event set occurrence time token which generated by PubNub service.
 */
=======
// Stores list of events which occurred on channel
// (presence events and message from other channel
// participants)
@property (nonatomic, readonly, strong) NSArray *events;

// Stores reference on event set occurrence time token
// which generated by PubNub service
>>>>>>> fix-pt65153600
@property (nonatomic, readonly, strong) NSNumber *timeToken;

#pragma mark -


@end
