workspace 'PubNub Tests'
install! 'cocoapods', :lock_pod_sources => false
use_frameworks!

abstract_target 'MockableTests' do
  pod 'PubNub', :path => '../'
  pod 'OCMock', '= 3.6'
  pod 'YAHTTPVCR'
 
  target '[macOS] Mocked Integration Tests' do
    platform :osx, '11.00'
  end

  target '[tvOS] Mocked Integration Tests' do
    platform :tvos, '14.0'
  end

  target '[iOS] Mocked Integration Tests' do
    platform :ios, '14.0'
  end

  target '[macOS] Unit Tests' do
    platform :osx, '11.00'
  end

  target '[tvOS] Unit Tests' do
    platform :tvos, '14.0'
  end

  target '[iOS] Unit Tests' do
    platform :ios, '14.0'
  end
end

target '[iOS] Integration Tests' do
  platform :ios, '14.0'
  pod 'PubNub', :path => '../'
end


abstract_target 'ContractTests' do
  pod 'Cucumberish', :git => 'https://github.com/parfeon/Cucumberish.git', :branch => 'master', :inhibit_warnings => true
  pod 'PubNub', :path => '../'

  target '[iOS] Contract Tests' do
    platform :ios, '14.0'
  end

  target '[iOS] Contract Tests Beta' do
    platform :ios, '14.0'
  end
end


# Making all interfaces visible for all targets on explicit import
pre_install do |installer_representation|
    installer_representation.aggregate_targets.each do |aggregate_target|
        aggregate_target.spec_consumers.each do |spec_consumer|
            unless spec_consumer.private_header_files.empty?
                spec_consumer.spec.attributes_hash['private_header_files'].clear
            end 
        end
    end
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited) PUBNUB_DISABLE_LOGGER=1'
            config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = target.name =~ /PubNub/ ? 'YES' : 'NO'
            config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        end
    end
end
