source "https://github.com/CocoaPods/Specs"

xcodeproj "PubNub Tests"
workspace "../PubNub"

target :ios do
  platform :ios, "7.0"
  link_with "iOS Tests"
  pod "Expecta", "~> 1.0"
  #pod "OHHTTPStubs", "~> 4.0"
  pod "JSZVCR", :git => 'https://github.com/jzucker2/JSZVCR.git', :branch => 'master'
  pod "PubNub", :path => "../"
end
