<<<<<<< HEAD
/**
 Extending \b PNChannelEvents class with properties and methods which can be used internally by \b PubNub client.

 @author Sergey Mamontov
 @version 3.4.0
 @copyright © 2009-13 PubNub Inc.
 */
=======
//
//  PNChannelEvents+Protected.h
//  pubnub
//
//  This header file used by library internal
//  components which require to access to some
//  methods and properties which shouldn't be
//  visible to other application components
//
//  Created by Sergey Mamontov.
//
//
>>>>>>> fix-pt65153600

#import "PNChannelEvents.h"


#pragma mark Protected interface methods

<<<<<<< HEAD
@interface PNChannelEvents ()
=======
@interface PNChannelEvents (Protected)
>>>>>>> fix-pt65153600


#pragma mark - Properties

<<<<<<< HEAD

@property (nonatomic, strong) NSArray *events;
=======
// Stores list of events which occurred on channel (presence events and message from other channel participants)
@property (nonatomic, strong) NSArray *events;

// Stores reference on event set occurrence time token which generated by PubNub service
>>>>>>> fix-pt65153600
@property (nonatomic, strong) NSNumber *timeToken;

#pragma mark -


@end
