#import "PubNub+Publish.h"
#import "PNPublishFileMessageRequest+Private.h"
#import "PNBasePublishRequest+Private.h"
#import "PubNub+CorePrivate.h"
#import "PNStatus+Private.h"
#import "PNHelpers.h"

// Deprecated
#import "PNAPICallBuilder+Private.h"


NS_ASSUME_NONNULL_BEGIN

#pragma mark Private interface declaration

@interface PubNub (PublishProtected)


#pragma mark - Composite message publish

/// Send provided Foundation object to the **PubNub** network.
///
/// - Parameters:
///   - message: Object (`NSString`, `NSNumber`, `NSArray`, `NSDictionary`) which will be published.
///   - channel: Name of the channel to which message should be published.
///   - payloads: Dictionary with payloads for different vendors (Apple with `'apns'` key and Google with `'gcm'`).
///   - shouldStore: Whether message should be stored and available with history API or not.
///   - ttl: How long message should be stored in channel's storage. If **0** it will be stored forever or if
///   `nil` - depends from account configuration.
///   - compressed Whether message should be compressed before sending or not.
///   - replicate: Whether message should be replicated across the **PubNub** network and sent simultaneously to all
///   subscribed clients on a channel.
///   - customMessageType: User-specified message type.
///   - metadata: `NSDictionary` with values which should be used by **PubNub** network to filter messages.
///   - queryParameters: List arbitrary query parameters which should be sent along with original API call.
///   - block: Publish completion block which.
- (void)publish:(nullable id)message
            toChannel:(NSString *)channel
    mobilePushPayload:(nullable NSDictionary<NSString *, id> *)payloads
       storeInHistory:(BOOL)shouldStore
                  ttl:(nullable NSNumber *)ttl
           compressed:(BOOL)compressed
      withReplication:(BOOL)replicate
    customMessageType:(nullable NSString *)customMessageType
             metadata:(nullable NSDictionary<NSString *, id> *)metadata
      queryParameters:(nullable NSDictionary *)queryParameters
           completion:(nullable PNPublishCompletionBlock)block;


#pragma mark - Signal

/// Send provided Foundation object to **PubNub** service.
///
/// Provided object will be serialized into JSON string before pushing to **PubNub** service. If client has been
/// configured with cipher key message will be encrypted as well.
///
/// - Parameters:
///   - message Object (`NSString`, `NSNumber`, `NSArray`, `NSDictionary`) which will be sent with signal.
///   - channel: Name of the channel to which signal should be sent.
///   - customMessageType: User-specified message type.
///   - queryParameters: List arbitrary query parameters which should be sent along with original API call.
///   - block: Signal completion block.
- (void)signal:(id)message
                channel:(NSString *)channel
      customMessageType:(nullable NSString *)customMessageType
    withQueryParameters:(nullable NSDictionary *)queryParameters
             completion:(nullable PNSignalCompletionBlock)block;


#pragma mark - Handlers

/// Handle publish builder perform with block call.
///
/// > Note: Logic moved into separate method because it shared between two almost identical API calls (regular publish
/// and fire which doesn't store message in storage and won't replicate it).
///
/// - Parameters:
///   - flags: List of conditional flags which has been generated by builder on user request.
///   - parameters: List of user-provided data which will be consumed by used API endpoint.
- (void)handlePublishBuilderExecutionWithFlags:(NSArray<NSString *> *)flags parameters:(NSDictionary *)parameters;

#pragma mark -


@end

NS_ASSUME_NONNULL_END


#pragma mark - Interface implementation

@implementation PubNub (Publish)


#pragma mark - Publish API builder interface (deprecated)

- (PNPublishFileMessageAPICallBuilder * (^)(void))publishFileMessage {
    [self.logger warnWithLocation:@"PubNub" andMessageFactory:^PNLogEntry * {
        return [PNStringLogEntry entryWithMessage:@"Builder-based interface deprecated. Please use corresponding "
                "request-based interfaces."];
    }];
    
    PNPublishFileMessageAPICallBuilder *builder = nil;
    __weak __typeof(self) weakSelf = self;
    
    builder = [PNPublishFileMessageAPICallBuilder builderWithExecutionBlock:^(NSArray<NSString *> *flags,
                                                                              NSDictionary *parameters) {
        NSString *identifier = parameters[NSStringFromSelector(@selector(fileIdentifier))];
        NSString *filename = parameters[NSStringFromSelector(@selector(fileName))];
        NSString *channel = parameters[NSStringFromSelector(@selector(channel))];
        NSNumber *shouldStore = parameters[NSStringFromSelector(@selector(shouldStore))];
        NSNumber *ttl = parameters[NSStringFromSelector(@selector(ttl))];

        if (shouldStore && !shouldStore.boolValue) ttl = nil;

        PNPublishFileMessageRequest *request = [PNPublishFileMessageRequest requestWithChannel:channel
                                                                                fileIdentifier:identifier
                                                                                          name:filename];
        request.customMessageType = parameters[NSStringFromSelector(@selector(customMessageType))];
        request.metadata = parameters[NSStringFromSelector(@selector(metadata))];
        request.message = parameters[NSStringFromSelector(@selector(message))];
        request.arbitraryQueryParameters = parameters[@"queryParam"];
        request.store = shouldStore ? shouldStore.boolValue : YES;
        request.ttl = ttl.unsignedIntegerValue;
        
        [weakSelf publishFileMessageWithRequest:request completion:parameters[@"block"]];
    }];
    
    return ^PNPublishFileMessageAPICallBuilder * {
        return builder;
    };
}

- (PNPublishAPICallBuilder * (^)(void))publish {
    [self.logger warnWithLocation:@"PubNub" andMessageFactory:^PNLogEntry * {
        return [PNStringLogEntry entryWithMessage:@"Builder-based interface deprecated. Please use corresponding "
                "request-based interfaces."];
    }];
    
    PNPublishAPICallBuilder *builder = nil;
    __weak __typeof(self) weakSelf = self;

    builder = [PNPublishAPICallBuilder builderWithExecutionBlock:^(NSArray<NSString *> *flags,
                                                                   NSDictionary *parameters) {
        [weakSelf handlePublishBuilderExecutionWithFlags:flags parameters:parameters];
    }];
    
    return ^PNPublishAPICallBuilder * {
        return builder;
    };
}

- (PNPublishAPICallBuilder * (^)(void))fire {
    [self.logger warnWithLocation:@"PubNub" andMessageFactory:^PNLogEntry * {
        return [PNStringLogEntry entryWithMessage:@"Builder-based interface deprecated. Please use corresponding "
                "request-based interfaces."];
    }];
    
    PNPublishAPICallBuilder *builder = nil;
    __weak __typeof(self) weakSelf = self;

    builder = [PNPublishAPICallBuilder builderWithExecutionBlock:^(NSArray<NSString *> *flags,
                                                                   NSDictionary *parameters) {
        [weakSelf handlePublishBuilderExecutionWithFlags:flags parameters:parameters];
    }];

    [builder setValue:@NO forParameter:NSStringFromSelector(@selector(shouldStore))];
    [builder setValue:@NO forParameter:NSStringFromSelector(@selector(replicate))];
    
    return ^PNPublishAPICallBuilder * {
        return builder;
    };
}

- (PNSignalAPICallBuilder * (^)(void))signal {
    [self.logger warnWithLocation:@"PubNub" andMessageFactory:^PNLogEntry * {
        return [PNStringLogEntry entryWithMessage:@"Builder-based interface deprecated. Please use corresponding "
                "request-based interfaces."];
    }];
    
    PNSignalAPICallBuilder * builder = nil;
    __weak __typeof(self) weakSelf = self;
    builder = [PNSignalAPICallBuilder builderWithExecutionBlock:^(NSArray<NSString *> *flags,
                                                                  NSDictionary *parameters) {
        NSString *customMessageType = parameters[NSStringFromSelector(@selector(customMessageType))];
        id message = parameters[NSStringFromSelector(@selector(message))];
        NSString *channel = parameters[NSStringFromSelector(@selector(channel))];
        NSDictionary *queryParam = parameters[@"queryParam"];
        id block = parameters[@"block"];
        
        [weakSelf signal:message
                 channel:channel
       customMessageType:customMessageType
     withQueryParameters:queryParam
              completion:block];
    }];
    
    return ^PNSignalAPICallBuilder * {
        return builder;
    };
}


#pragma mark - Files message

- (void)publishFileMessageWithRequest:(PNPublishFileMessageRequest *)userRequest
                           completion:(PNPublishCompletionBlock)block {
    if (!userRequest.retried) userRequest.sequenceNumber = [self.sequenceManager nextSequenceNumber:YES];
    if (!userRequest.cryptoModule) userRequest.cryptoModule = self.configuration.cryptoModule;
    PNOperationDataParser *responseParser = [self parserWithStatus:[PNPublishStatus class]];
    PNParsedRequestCompletionBlock handler;

    PNWeakify(self);
    handler = ^(PNTransportRequest *request, id<PNTransportResponse> response, __unused NSURL *location,
                PNOperationDataParseResult<PNPublishStatus *, PNPublishStatus *> *result) {
        PNStrongify(self);

        if (!result.status.isError && !userRequest.publishOnFileSharing) {
            [self.logger debugWithLocation:@"PubNub" andMessageFactory:^PNLogEntry * {
                return [PNStringLogEntry entryWithMessage:PNStringFormat(@"Publish file message success. File message "
                                                                         "published with timetoken: %@",
                                                                         result.status.data.timetoken)];
            }];
        }

        [self callBlock:block status:YES withResult:nil andStatus:result.status];
    };
                               
    [self.logger debugWithLocation:@"PubNub" andMessageFactory:^PNLogEntry * {
        return [PNDictionaryLogEntry entryWithMessage:[userRequest dictionaryRepresentation]
                                              details:@"Publish file message with parameters:"];
    }];

    [self performRequest:userRequest withParser:responseParser completion:handler];
}


#pragma mark - Plain message publish

- (void)publishWithRequest:(PNPublishRequest *)userRequest completion:(PNPublishCompletionBlock)block {
    if (!userRequest.retried) userRequest.sequenceNumber = [self.sequenceManager nextSequenceNumber:YES];
    if (!userRequest.cryptoModule) userRequest.cryptoModule = self.configuration.cryptoModule;
    PNOperationDataParser *responseParser = [self parserWithStatus:[PNPublishStatus class]];
    PNParsedRequestCompletionBlock handler;

    PNWeakify(self);
    handler = ^(PNTransportRequest *request, id<PNTransportResponse> response, __unused NSURL *location,
                PNOperationDataParseResult<PNPublishStatus *, PNPublishStatus *> *result) {
        PNStrongify(self);

        if (!result.status.isError) {
            [self.logger debugWithLocation:@"PubNub" andMessageFactory:^PNLogEntry * {
                return [PNStringLogEntry entryWithMessage:PNStringFormat(@"Publish success with timetoken: %@",
                                                                         result.status.data.timetoken)];
            }];
        }

        [self callBlock:block status:YES withResult:nil andStatus:result.status];
    };
    
    [self.logger debugWithLocation:@"PubNub" andMessageFactory:^PNLogEntry * {
        return [PNDictionaryLogEntry entryWithMessage:[userRequest dictionaryRepresentation]
                                              details:@"Publish with parameters:"];
    }];

    [self performRequest:userRequest withParser:responseParser completion:handler];
}

- (void)publish:(id)message toChannel:(NSString *)channel withCompletion:(PNPublishCompletionBlock)block {
    [self.logger warnWithLocation:@"PubNub" andMessageFactory:^PNLogEntry * {
        return [PNStringLogEntry entryWithMessage:@"This method deprecated. Please use "
                "'-publishWithRequest:completion:' method instead."];
    }];
    
    [self publish:message toChannel:channel withMetadata:nil completion:block];
}

- (void)publish:(id)message
       toChannel:(NSString *)channel
    withMetadata:(NSDictionary<NSString *, id> *)metadata
      completion:(PNPublishCompletionBlock)block {
    [self.logger warnWithLocation:@"PubNub" andMessageFactory:^PNLogEntry * {
        return [PNStringLogEntry entryWithMessage:@"This method deprecated. Please use "
                "'-publishWithRequest:completion:' method instead."];
    }];
    
    [self publish:message toChannel:channel compressed:NO withMetadata:metadata completion:block];
}

- (void)publish:(id)message
         toChannel:(NSString *)channel
        compressed:(BOOL)compressed
    withCompletion:(PNPublishCompletionBlock)block {
    [self.logger warnWithLocation:@"PubNub" andMessageFactory:^PNLogEntry * {
        return [PNStringLogEntry entryWithMessage:@"This method deprecated. Please use "
                "'-publishWithRequest:completion:' method instead."];
    }];
    
    [self publish:message toChannel:channel compressed:compressed withMetadata:nil completion:block];
}

- (void)publish:(id)message
       toChannel:(NSString *)channel
      compressed:(BOOL)compressed
    withMetadata:(NSDictionary<NSString *, id> *)metadata
      completion:(PNPublishCompletionBlock)block {
    [self.logger warnWithLocation:@"PubNub" andMessageFactory:^PNLogEntry * {
        return [PNStringLogEntry entryWithMessage:@"This method deprecated. Please use "
                "'-publishWithRequest:completion:' method instead."];
    }];
    
    [self publish:message
         toChannel:channel
    storeInHistory:YES
        compressed:compressed
      withMetadata:metadata
        completion:block];
}

- (void)publish:(id)message
         toChannel:(NSString *)channel
    storeInHistory:(BOOL)shouldStore
    withCompletion:(PNPublishCompletionBlock)block {
    [self.logger warnWithLocation:@"PubNub" andMessageFactory:^PNLogEntry * {
        return [PNStringLogEntry entryWithMessage:@"This method deprecated. Please use "
                "'-publishWithRequest:completion:' method instead."];
    }];
    
    [self publish:message toChannel:channel storeInHistory:shouldStore withMetadata:nil completion:block];
}

- (void)publish:(id)message
         toChannel:(NSString *)channel
    storeInHistory:(BOOL)shouldStore
      withMetadata:(NSDictionary<NSString *, id> *)metadata
        completion:(PNPublishCompletionBlock)block {
    [self.logger warnWithLocation:@"PubNub" andMessageFactory:^PNLogEntry * {
        return [PNStringLogEntry entryWithMessage:@"This method deprecated. Please use "
                "'-publishWithRequest:completion:' method instead."];
    }];
    
    [self publish:message
         toChannel:channel
    storeInHistory:shouldStore
        compressed:NO
      withMetadata:metadata
        completion:block];
}

- (void)publish:(id)message
         toChannel:(NSString *)channel
    storeInHistory:(BOOL)shouldStore
        compressed:(BOOL)compressed
    withCompletion:(PNPublishCompletionBlock)block {
    [self.logger warnWithLocation:@"PubNub" andMessageFactory:^PNLogEntry * {
        return [PNStringLogEntry entryWithMessage:@"This method deprecated. Please use "
                "'-publishWithRequest:completion:' method instead."];
    }];
    
    [self publish:message
         toChannel:channel
    storeInHistory:shouldStore
        compressed:compressed
      withMetadata:nil
        completion:block];
}

- (void)publish:(id)message
         toChannel:(NSString *)channel
    storeInHistory:(BOOL)shouldStore
        compressed:(BOOL)compressed
      withMetadata:(NSDictionary<NSString *, id> *)metadata
        completion:(PNPublishCompletionBlock)block {
    [self.logger warnWithLocation:@"PubNub" andMessageFactory:^PNLogEntry * {
        return [PNStringLogEntry entryWithMessage:@"This method deprecated. Please use "
                "'-publishWithRequest:completion:' method instead."];
    }];
    
    [self publish:message
            toChannel:channel
    mobilePushPayload:nil
       storeInHistory:shouldStore
           compressed:compressed
         withMetadata:metadata
           completion:block];
}


#pragma mark - Composite message publish

- (void)publish:(id)message
            toChannel:(NSString *)channel
    mobilePushPayload:(NSDictionary<NSString *, id> *)payloads
       withCompletion:(PNPublishCompletionBlock)block {
    [self.logger warnWithLocation:@"PubNub" andMessageFactory:^PNLogEntry * {
        return [PNStringLogEntry entryWithMessage:@"This method deprecated. Please use "
                "'-publishWithRequest:completion:' method instead."];
    }];
    
    [self publish:message toChannel:channel mobilePushPayload:payloads withMetadata:nil completion:block];
}

- (void)publish:(id)message
            toChannel:(NSString *)channel
    mobilePushPayload:(NSDictionary<NSString *, id> *)payloads
         withMetadata:(NSDictionary<NSString *, id> *)metadata
           completion:(PNPublishCompletionBlock)block {
    [self.logger warnWithLocation:@"PubNub" andMessageFactory:^PNLogEntry * {
        return [PNStringLogEntry entryWithMessage:@"This method deprecated. Please use "
                "'-publishWithRequest:completion:' method instead."];
    }];
    
    [self publish:message
            toChannel:channel
    mobilePushPayload:payloads
           compressed:NO
         withMetadata:metadata
           completion:block];
}

- (void)publish:(id)message
            toChannel:(NSString *)channel
    mobilePushPayload:(NSDictionary<NSString *, id> *)payloads
           compressed:(BOOL)compressed
       withCompletion:(PNPublishCompletionBlock)block {
    [self.logger warnWithLocation:@"PubNub" andMessageFactory:^PNLogEntry * {
        return [PNStringLogEntry entryWithMessage:@"This method deprecated. Please use "
                "'-publishWithRequest:completion:' method instead."];
    }];
    
    [self publish:message
            toChannel:channel
    mobilePushPayload:payloads
           compressed:compressed
         withMetadata:nil
           completion:block];
}

- (void)publish:(id)message
            toChannel:(NSString *)channel
    mobilePushPayload:(NSDictionary<NSString *, id> *)payloads
           compressed:(BOOL)compressed
         withMetadata:(NSDictionary<NSString *, id> *)metadata
           completion:(PNPublishCompletionBlock)block {
    [self.logger warnWithLocation:@"PubNub" andMessageFactory:^PNLogEntry * {
        return [PNStringLogEntry entryWithMessage:@"This method deprecated. Please use "
                "'-publishWithRequest:completion:' method instead."];
    }];
    
    [self publish:message
            toChannel:channel
    mobilePushPayload:payloads
       storeInHistory:YES
           compressed:compressed
         withMetadata:metadata
           completion:block];
}

- (void)publish:(id)message
            toChannel:(NSString *)channel
    mobilePushPayload:(NSDictionary<NSString *, id> *)payloads
       storeInHistory:(BOOL)shouldStore
       withCompletion:(PNPublishCompletionBlock)block {
    [self.logger warnWithLocation:@"PubNub" andMessageFactory:^PNLogEntry * {
        return [PNStringLogEntry entryWithMessage:@"This method deprecated. Please use "
                "'-publishWithRequest:completion:' method instead."];
    }];
    
    [self publish:message
            toChannel:channel
    mobilePushPayload:payloads
       storeInHistory:shouldStore
         withMetadata:nil
           completion:block];
}

- (void)publish:(id)message
            toChannel:(NSString *)channel
    mobilePushPayload:(NSDictionary<NSString *, id> *)payloads
       storeInHistory:(BOOL)shouldStore
         withMetadata:(NSDictionary<NSString *, id> *)metadata
           completion:(PNPublishCompletionBlock)block {
    [self.logger warnWithLocation:@"PubNub" andMessageFactory:^PNLogEntry * {
        return [PNStringLogEntry entryWithMessage:@"This method deprecated. Please use "
                "'-publishWithRequest:completion:' method instead."];
    }];
    
    [self publish:message
            toChannel:channel
    mobilePushPayload:payloads
       storeInHistory:shouldStore
           compressed:NO
         withMetadata:metadata
           completion:block];
}

- (void)publish:(id)message
            toChannel:(NSString *)channel
    mobilePushPayload:(NSDictionary<NSString *, id> *)payloads
       storeInHistory:(BOOL)shouldStore
           compressed:(BOOL)compressed
       withCompletion:(PNPublishCompletionBlock)block {
    [self.logger warnWithLocation:@"PubNub" andMessageFactory:^PNLogEntry * {
        return [PNStringLogEntry entryWithMessage:@"This method deprecated. Please use "
                "'-publishWithRequest:completion:' method instead."];
    }];
    
    [self publish:message
            toChannel:channel
    mobilePushPayload:payloads
       storeInHistory:shouldStore
           compressed:compressed
         withMetadata:nil
           completion:block];
}

- (void)publish:(id)message
            toChannel:(NSString *)channel
    mobilePushPayload:(NSDictionary<NSString *, id> *)payloads
       storeInHistory:(BOOL)shouldStore
           compressed:(BOOL)compressed
         withMetadata:(NSDictionary<NSString *, id> *)metadata
           completion:(PNPublishCompletionBlock)block {
    [self.logger warnWithLocation:@"PubNub" andMessageFactory:^PNLogEntry * {
        return [PNStringLogEntry entryWithMessage:@"This method deprecated. Please use "
                "'-publishWithRequest:completion:' method instead."];
    }];
    
    [self publish:message
            toChannel:channel
    mobilePushPayload:payloads
       storeInHistory:shouldStore
                  ttl:nil
           compressed:compressed
      withReplication:YES
    customMessageType:nil
             metadata:metadata
      queryParameters:nil
           completion:block];
}

- (void)publish:(id)message
            toChannel:(NSString *)channel
    mobilePushPayload:(NSDictionary<NSString *, id> *)payloads
       storeInHistory:(BOOL)shouldStore
                  ttl:(NSNumber *)ttl
           compressed:(BOOL)compressed
      withReplication:(BOOL)replicate
    customMessageType:(nullable NSString *)customMessageType
             metadata:(NSDictionary<NSString *, id> *)metadata
      queryParameters:(NSDictionary *)queryParameters
           completion:(PNPublishCompletionBlock)block {

    PNPublishRequest *request = [PNPublishRequest requestWithChannel:channel];

    request.arbitraryQueryParameters = queryParameters;
    request.customMessageType = customMessageType;
    request.replicate = replicate;
    request.compress = compressed;
    request.metadata = metadata;
    request.payloads = payloads;
    request.store = shouldStore;
    request.message = message;

    if (ttl) request.ttl = ttl.unsignedIntegerValue;

    [self publishWithRequest:request completion:block];
}


#pragma mark - Signal

- (void)sendSignalWithRequest:(PNSignalRequest *)userRequest completion:(PNSignalCompletionBlock)handlerBlock {
    PNOperationDataParser *responseParser = [self parserWithStatus:[PNSignalStatus class]];
    PNSignalCompletionBlock block = [handlerBlock copy];
    PNParsedRequestCompletionBlock handler;

    PNWeakify(self);
    handler = ^(PNTransportRequest *request, id<PNTransportResponse> response, __unused NSURL *location,
                PNOperationDataParseResult<PNSignalStatus *, PNSignalStatus *> *result) {
        PNStrongify(self);

        if (!result.status.isError) {
            [self.logger debugWithLocation:@"PubNub" andMessageFactory:^PNLogEntry * {
                return [PNStringLogEntry entryWithMessage:PNStringFormat(@"Signal success with timetoken: %@",
                                                                         result.status.data.timetoken)];
            }];
        }

        [self callBlock:block status:YES withResult:nil andStatus:result.status];
    };
    
    [self.logger debugWithLocation:@"PubNub" andMessageFactory:^PNLogEntry * {
        return [PNDictionaryLogEntry entryWithMessage:[userRequest dictionaryRepresentation]
                                              details:@"Signal with parameters:"];
    }];

    [self performRequest:userRequest withParser:responseParser completion:handler];
}

- (void)signal:(id)message channel:(NSString *)channel withCompletion:(PNSignalCompletionBlock)block {
    [self.logger warnWithLocation:@"PubNub" andMessageFactory:^PNLogEntry * {
        return [PNStringLogEntry entryWithMessage:@"This method deprecated. Please use "
                "'-sendSignalWithRequest:completion:' method instead."];
    }];
    
    [self signal:message channel:channel customMessageType:nil withQueryParameters:nil completion:block];
}

- (void)signal:(id)message
                channel:(NSString *)channel
      customMessageType:(nullable NSString *)customMessageType
    withQueryParameters:(NSDictionary *)queryParameters
             completion:(PNSignalCompletionBlock)block {

    PNSignalRequest *request = [PNSignalRequest requestWithChannel:channel signal:message];
    request.customMessageType = customMessageType;
    request.arbitraryQueryParameters = queryParameters;
    [self sendSignalWithRequest:request completion:block];
}


#pragma mark - Handlers

- (void)handlePublishBuilderExecutionWithFlags:(NSArray<NSString *> *)flags parameters:(NSDictionary *)parameters {
    NSNumber *shouldStore = parameters[NSStringFromSelector(@selector(shouldStore))];
    NSNumber *ttl = parameters[NSStringFromSelector(@selector(ttl))];
    NSNumber *compressed = parameters[NSStringFromSelector(@selector(compress))];
    NSNumber *replicate = parameters[NSStringFromSelector(@selector(replicate))];

    if (shouldStore && !shouldStore.boolValue) ttl = nil;
    
    [self publish:parameters[NSStringFromSelector(@selector(message))]
            toChannel:parameters[NSStringFromSelector(@selector(channel))]
    mobilePushPayload:parameters[NSStringFromSelector(@selector(payloads))]
       storeInHistory:(shouldStore ? shouldStore.boolValue : YES)
                  ttl:ttl
           compressed:compressed.boolValue
      withReplication:(replicate ? replicate.boolValue : YES)
    customMessageType:parameters[NSStringFromSelector(@selector(customMessageType))]
             metadata:parameters[NSStringFromSelector(@selector(metadata))]
      queryParameters:parameters[@"queryParam"]
           completion:parameters[@"block"]];
}

#pragma mark -


@end
