source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5'
pod 'CocoaLumberjack'

target :PubNubTestTests, :exclusive => true do
  pod 'OCHamcrest', '~> 4.0'
  pod 'OCMockito', '~> 1.0'
end
