#fastlane_version "1.104.0"
#update_fastlane

desc "Run iOS tests against devices specified in Travis jobs matrix."
desc "The lane to run by Travis-CI on every commit or merge pull request."
lane :test_ios do |options|
  scan(
    sdk: 'iphonesimulator',
    devices: devices,
    configuration: options[:configuration],
    scheme: scheme(options[:language])
  )
end

desc "Run tvOS tests against devices specified in Travis jobs matrix."
desc "The lane to run by Travis-CI on every commit or merge pull request."
lane :test_tvos do |options|
  scan(
    sdk: 'appletvsimulator',
    device: devices,
    configuration: options[:configuration],
    scheme: scheme(options[:language])
  )
end

desc "Run macOS tests."
desc "The lane to run by Travis-CI on every commit or merge pull request."
lane :test_macos do |options|
  scan(
    configuration: options[:configuration],
    scheme: scheme(options[:language])
  )
end

desc "Compose list of devices against which tests should be performed."
def devices  
  # Fetch available device names list
  devices_names = ENV["PN_TEST_OS_DEVICES"].split(',')
  
  devices_names.map { |device_name| "#{device_name} (#{ENV['PN_TEST_OS_VERSION']})" }
end

def scheme(language)
  "#{ENV['PN_TEST_OS_SCHEME']} (#{language})"
end
