source 'git@github.com:parfeon/pubnub-private-pods-repo.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod "PubNubBridge"

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['GCC_INSTRUMENT_PROGRAM_FLOW_ARCS'] = 'NO'
            config.build_settings['GCC_GENERATE_TEST_COVERAGE_FILES'] = 'NO'
            if target.name == "CocoaLumberjack"
                config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
            end
            if target.name == "OHHTTPStubs"
                config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
            end
        end
    end
end