source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
link_with 'PubNub', 'PubNub Static'
pod 'AFNetworking', '~> 2.5'
pod 'CocoaLumberjack'

post_install do |installer_representation|
    installer_representation.project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end