#import <Foundation/Foundation.h>


/**
 This class allow to describe set of events which occurred on one of the channels and passed to the user.

 @author Sergey Mamontov
 @version 3.4.0
 @copyright © 2009-13 PubNub Inc.
 */
@interface PNChannelEvents : NSObject


#pragma mark Properties

/**
 Stores list of events which occurred on channel (presence events and message from other channel participants).
 */
@property (nonatomic, readonly, strong) NSArray *events;

/**
 Stores reference on event set occurrence time token which generated by PubNub service.
 */
@property (nonatomic, readonly, strong) NSNumber *timeToken;

#pragma mark -


@end
