#import "PNResponseParser.h"

/**
 This class used to initiate parser which is able to parse events which generated by \b PubNub service over subscribe
 channels.

 @author Sergey Mamontov
 @version 3.4.0
 @copyright © 2009-13 PubNub Inc.
 */
@interface PNChannelEventsResponseParser : PNResponseParser


#pragma mark -


@end
