name: Automated product release

on:
  pull_request:
    branches: [master]
    types: [closed]
env:
  LANG: en_US.UTF-8
  LANGUAGE: en_US.UTF-8
  LC_ALL: en_US.UTF-8
  LC_CTYPE: en_US.UTF-8

jobs:
  check-release:
    name: Check release required
    if: github.event.pull_request.merged && endsWith(github.repository, '-private') != true
    runs-on:
      group: Default
    outputs:
      release: ${{ steps.check.outputs.ready }}
    steps:
      - name: Checkout actions
        uses: actions/checkout@v4
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: v1
          token: ${{ secrets.GH_TOKEN }}
          path: .github/.release/actions
      - id: check
        name: Check pre-release completed
        uses: ./.github/.release/actions/actions/checks/release
        with:
          token: ${{ secrets.GH_TOKEN }}
  publish:
    name: Publish package
    needs: check-release
    if: needs.check-release.outputs.release == 'true'
    runs-on:
      group: macos-gh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # This should be the same as the one specified for on.pull_request.branches
          ref: master
      - name: Checkout actions
        uses: actions/checkout@v4
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: v1
          token: ${{ secrets.GH_TOKEN }}
          path: .github/.release/actions
      - name: Setup Ruby 3.2.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Setup CocoaPods
        run: gem install cocoapods
      - name: Publish to CocoaPods Trunk
        uses: ./.github/.release/actions/actions/services/cocoapods
        with:
          token: ${{ secrets.GH_TOKEN }}
          cocoapods-token: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      - name: Create Release
        uses: ./.github/.release/actions/actions/services/github-release
        with:
          token: ${{ secrets.GH_TOKEN }}
          artifacts-folder: .github/.release/artifacts
          last-service: true
      - name: Upload test reports
        uses: ./.github/.release/actions/actions/test-reports/upload
        with:
          token: ${{ secrets.GH_TOKEN }}
          acceptance-tests-workflow: Tests
